<?php

/**
 * @file
 * Functions for the migrate_default_content module.
 */

/**
 * Implements hook_migration_plugins_alter().
 *
 * Create migrations based on data files.
 */
function migrate_default_content_migration_plugins_alter(&$definitions) {
  $mdc_definitions = \Drupal::service('migrate_default_content.migration_generator')->generateMigrations();
  $definitions = array_merge($definitions, $mdc_definitions);
}
